### PR TITLE
Titan I realplumes

### PR DESCRIPTION
**Pull request by zorg2044**

### CODE REVIEW

**Comment by zorg2044** [comment]
Um I took the liberty of modifying the LR87-AJ3 config. The existing config applies the blanket LR87 type to the model but I beleive that would cause it to have all the LR87 modes as selectable rather than just the aj3. It also wasnt appearing in game for some reason. I changed the engine patch to the same syntax as the others.

This PR covers the plumes for all the Titan I liquid engines now

**Comment by mcd0uble** [comment]
Thanks, fwiw some of the engine configs I've done are probably not optimal for engines that have multiple ModuleEnginesFX for verniers etc. I couldn't figure out how to apply an engineType to the part so multiple configs could be selected without all the plumes disappearing.

It's probably best anyway for the AJ3 variants to be just the kerolox version but it would be nice to be able to apply the blanket LR91 config to the others, so you can use them as the LR91-9, LR91-11A, etc

**Comment by zorg2044** [comment]
@mcd0uble Titan II is WIP but you can set up the engine modes manually. Rather than setting up a broad engine type, you manually set up the relelavant subtype configs. This seems to work although not fully tested. Might need to use B9 instead where engine configs are associated with mesh switches such as the LR87 single or the new Thor LR79.

https://github.com/zorg2044/BDB-RO/blob/c8d6122833a76ad85c93079f786f7a82a2e647a9/BDB_RO_configs/RO_BDB_engines.cfg#L737

**Comment by mcd0uble** [comment]
oh that's a good idea, I think though with the LR87 numbers you've got the thrust for one chamber there, so you'd have to double it. When using engineType = LR87 it's engineTypeMult = 2 that does that usually.

The engines with B9 switches for engine configs I've just sorta removed the B9 module and used engineType so you can select the config that way and use B9 to select different meshes, but there's probably a better way to do that too.

**Comment by zorg2044** [comment]
Oh good catch on the thrust thing. Will keep that in mind.

I believe the B9 switch will probably work with the RO engine module. So it can be made to work just like the stock B9 switch (stats+mesh). That does mean a slightly different UI for selecting the engine type compared to other RO multi mode engines but its prob not a big deal as you need to switch the mesh anyway using B9.

**Pull request merged**
